projectRoot = 'D:\MyDesktop\MMSC Materials\Case Study _ SC\Project_Image_Colourisation\ImageColourisationApp';
addpath(fullfile(projectRoot,'lib'));
addpath(fullfile(projectRoot,'KernelFcns'));
addpath(fullfile(projectRoot,'ImgRecoveryAlg'));

imgFile  = fullfile(projectRoot,'Pics','peppers.png');
orig     = imread(imgFile);
grey3ch  = genGreyImg(imgFile);

mask     = genUnif(orig, 2); 
comb     = combineMaskedImg(orig, grey3ch, mask);


paramsA = struct(...
  'sigma1', 100,  ...
  'sigma2', 100, ...
  'p',      0.5, ...
  'delta',  2e-4,...
  'kernel', "Gaussian", ...
  'round',  "MinMax"    ...
);
paramsB = struct(...
  'sigma1', 486.0072 , ...
  'sigma2', 25.0140, ...
  'p',      0.5521, ...
  'delta',  2e-4,...
  'kernel', "Gaussian", ...
  'round',  "MinMax"    ...
);

revA = imgRecBuildin(...
  comb, grey3ch, mask, ...
  paramsA.sigma1, paramsA.sigma2, paramsA.p, paramsA.delta, ...
  paramsA.kernel, paramsA.round);

revB = imgRecBuildin(...
  comb, grey3ch, mask, ...
  paramsB.sigma1, paramsB.sigma2, paramsB.p, paramsB.delta, ...
  paramsB.kernel, paramsB.round);

figure('Name','Reconstruction Comparison','NumberTitle','off');
tl = tiledlayout(1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax1 = nexttile;
imshow(revA,'Parent',ax1);
title(ax1, sprintf(...
  'Set A: σ₁=%d, σ₂=%d, p=%d', ...
  paramsA.sigma1, paramsA.sigma2, paramsA.p));
axis(ax1,'off');

ax2 = nexttile;
imshow(revB,'Parent',ax2);
title(ax2, sprintf(...
  'Set B: σ₁=%d, σ₂=%d, p=%d', ...
  paramsB.sigma1, paramsB.sigma2, paramsB.p));
axis(ax2,'off');
